### PR TITLE
Add maven build

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
The aim of this PR is to make the decoupled sources buildable and pass the CI testing.

- drop ant build
- move sources to standard maven layout
- add maven build (can any plugins be dropped?)

I have provided two ways of running the tests.  We will need to decide which is most useful.

- via maven profiles (to be similar to the ant targets).  But it forces a rebuild for every test invocation and is horribly complicated and verbose, both for the developer and the person invoking the tests (could be wrapped with a shell script though)
- via the bftest uberjar (we can add a wrapper script to call it)

There is likely other cleanup and improvement to be done, this is just the first step to make things build.  (The work here was done in October 2016.)

Testing: Check the builds are green.

### CODE REVIEW

**Comment by joshmoore** [comment]
Re-opening to see if the CIs are triggered.

**Comment by joshmoore** [comment]
Re-try after disabling/enabling travis.

**Comment by rleigh-codelibre** [comment]
Green in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-merge/20/

**Comment by joshmoore** [comment]
Build of this with https://github.com/ome/bio-formats-build/pull/11 works fine. I'm missing though what to set as the ENTRYPOINT in order to replace https://github.com/openmicroscopy/bioformats/blob/fb683ed5620594e27a62e9c7ef0de1a5dfca956d/Dockerfile

**Comment by joshmoore** [comment]
Discussed with @rleigh-codelibre today. Merging this so that the build can complete. The API here is incomplete and we'll need to discuss whether wrapper script or similar. Also, the removal of the test-suit is not intended for 5.8 so the changes here are a 5.9+ development.

**Pull request merged**
